# Generated by Django 4.2.6 on 2024-01-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_product_image_alter_product_rim_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="buyed",
            field=models.IntegerField(default=0, verbose_name="Покупки"),
        ),
        migrations.AlterField(
            model_name="product",
            name="rim_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Литые"),
                    ("4", "Штампованые"),
                    ("2", "Кованые"),
                    ("5", "Грузовые"),
                ],
                default="0",
                max_length=1,
                null=True,
                verbose_name="Тип дисков",
            ),
        ),
    ]
