# Generated by Django 4.2.6 on 2024-01-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shop",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Магазин",
                "verbose_name_plural": "Магазины",
            },
        ),
        migrations.AddField(
            model_name="shop",
            name="ig",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Instagram"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="phone",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="sort_order",
            field=models.IntegerField(default=1, verbose_name="Порядок"),
        ),
        migrations.AddField(
            model_name="shop",
            name="tg",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Телеграм"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="tk",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Tiktok"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="vk",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="ВК"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="wa",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Whatsapp"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="yt",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Youtube"
            ),
        ),
    ]
