# Generated by Django 4.2.6 on 2024-01-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0002_alter_shop_options_shop_ig_shop_phone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worktime",
            options={
                "ordering": ["day_of_week"],
                "verbose_name": "Время Работы",
                "verbose_name_plural": "Время Работы",
            },
        ),
        migrations.AlterField(
            model_name="worktime",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (1, "Понедельник"),
                    (2, "Вторник"),
                    (3, "Среда"),
                    (4, "Четверг"),
                    (5, "Пятница"),
                    (6, "Суббота"),
                    (7, "Воскресенье"),
                ],
                default=1,
                verbose_name="День недели",
            ),
        ),
    ]
